# This is a basic workflow to help you get started with Actions

name: pr-agent

# Controls when the workflow will run
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited]

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: ${{ github.event.sender.type != 'Bot' }}
    steps:
      - id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
          github_action.auto_describe: true
          github_action.auto_review:   true
          github_action.auto_improve:  false
